# File: .github/workflows/azcli.yml

on:
  workflow_dispatch:

name: AzureARMdeployment

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@main
     
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./template.json
        parameters: ./parameters.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
